openapi: 3.2.0
info:
  title: Birdeye User API
  version: '1.0'
  description: 'Operations tagged User across 2 of this provider''s published API definitions: birdeye-birdeye-api-openapi.yml, birdeye-openapi-original.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.birdeye.com
  description: Production
- url: https://api.birdeye.com/resources
tags:
- name: User
  description: Delete and manage user profiles and permissions easily.
paths:
  /v1/user/signup/v2:
    post:
      summary: Create User
      operationId: create-user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 1059
                  message: Last name cannot be more than 50 characters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                userEmailId:
                  type: string
                phone:
                  type: string
                userRole:
                  type: string
                sendInvite:
                  type: boolean
              required:
              - userEmailId
              - userRole
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/user/updateUser:
    put:
      summary: Update User
      operationId: update-user
      tags:
      - User
      parameters:
      - name: userEmailId
        in: query
        required: true
        description: Email id of the user to be updated
        schema:
          type: string
        example: abc@test.com
      - name: entUser
        in: query
        required: true
        description: 'true if the user needs to provide enterprise level access in case of all locations.

          entUser needs to be passed as true if user needs to be provided access to all locations otherwise by default its false.'
        schema:
          type: boolean
        example: 'false'
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 1189
                  message: User with given email id not found.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                locationsNumberAccess:
                  type: array
                user:
                  type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
                userRole:
                  type: string
                notification:
                  type: object
                  properties:
                    sendReviewEmailAlert:
                      type: number
                    sendDailyReviewDigest:
                      type: number
                    dailyDigestAbsoluteTime:
                      type: string
                    dailyDigestRunHour:
                      type: number
                    dailyDigestRunMinute:
                      type: number
                    sendWeeklyReviewDigest:
                      type: number
                    weeklyDigestAbsoluteTime:
                      type: string
                    weeklyDigestRunDay:
                      type: number
                    weeklyDigestRunHour:
                      type: number
                    weeklyDigestRunMinute:
                      type: number
                    sendReviewSmsAlert:
                      type: number
                    sendDailySocialDigest:
                      type: number
                    sendTicketAlert:
                      type: number
                    sendTicketStatusAlert:
                      type: number
                    sendTicketAssigneeChangeAlert:
                      type: number
                    sendTicketCommentAlert:
                      type: number
                    sendTicketStartOrStoppedWatchingAlert:
                      type: number
                    sendSurveyAlert:
                      type: number
                    sendReferralAlert:
                      type: number
                    sendScanToolSignUpAlert:
                      type: number
                    webChatEmailInterval:
                      type: string
                    webChatEmailAbsoluteTime:
                      type: string
                    enableWebchat:
                      type: number
                    enableTeamAlert:
                      type: number
                    reviewAlertRatings:
                      type: array
                    messengerEmailConversationType:
                      type: string
                    assignedToMeAlert:
                      type: number
                    enableBrowserNotification:
                      type: number
                    messengerReportEnable:
                      type: number
                    appointmentBooking:
                      type: number
                    appointmentFormsEnabled:
                      type: number
                    enableAIPostSuggestions:
                      type: number
                    enablePostFailureEmail:
                      type: number
                    enableDirectMessageEmail:
                      type: number
                    enablePostCommentsEmail:
                      type: number
                    enableMentionsEmail:
                      type: number
                    enableStoryMentionsEmail:
                      type: number
                    enableNewFollowersEmail:
                      type: number
                    enableRetweetEmail:
                      type: number
                    enableQuoteTweetEmail:
                      type: number
                    enablePostFailureBrowserNotification:
                      type: number
                    paymentAlert:
                      type: number
                    sendBrokenIntegrationAlert:
                      type: number
                    sendBrokenIntegrationEmail:
                      type: number
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/user/remove:
    delete:
      summary: Delete a user
      operationId: delete-a-user
      tags:
      - User
      parameters:
      - name: bid
        in: query
        required: true
        description: Business Id from which user access has to be revoked
        schema:
          type: string
        example: '123'
      - name: email
        in: query
        required: true
        description: Email id of the user whose access has to be revoked
        schema:
          type: string
        example: abc@test.com
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 1175
                  message: No business found with the given id
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/user/forgotpassword:
    post:
      summary: Forgot Password
      operationId: forgot-password
      tags:
      - User
      parameters:
      - name: email
        in: query
        required: true
        description: Email Id of the user whose access has to be revoked
        schema:
          type: string
        example: abc@test.com
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 1189
                  message: User with given email id not found.
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/user/details:
    get:
      summary: Get details of a user
      operationId: get-details-of-a-user
      tags:
      - User
      parameters:
      - name: email
        in: query
        required: true
        description: Email Id of the user whose details to be retrieved
        schema:
          type: string
        example: abc@test.com
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 1010
                  message: No user found with the given id
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
components:
  schemas:
    1167Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1167
        message: API key is missing
    1059Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1059
        message: Last name cannot be more than 50 characters
    1188Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1188
        message: User is not associated with the business.
    1033Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1033
        message: You are not authorized to perform this action
    Apiary_updateUser_Request:
      type: object
      properties:
        locationsNumberAccess:
          type: array
          description: Location Numbers list of which the user has access. Must provide full list each time, empty list grants access to all locations.
          items: {}
        user:
          type: object
          properties:
            firstName:
              type: string
              description: First name of the user.
            lastName:
              type: string
              description: The last name of the user.
          description: user details
        userRole:
          type: string
          description: Role to assign within the application.
        notification:
          type: object
          properties:
            sendReviewEmailAlert:
              type: number
              description: Flag to enable sending of review email alerts.
            sendDailyReviewDigest:
              type: number
              description: Flag to enable sending of daily review summary emails.
            dailyDigestAbsoluteTime:
              type: string
              description: Daily digest delivery time in HH:MM format.
            dailyDigestRunHour:
              type: number
              description: Hour component when daily digest is executed.
            dailyDigestRunMinute:
              type: number
              description: Minute component when daily digest is executed.
            sendWeeklyReviewDigest:
              type: number
              description: Flag to enable sending of weekly review summary emails.
            weeklyDigestAbsoluteTime:
              type: string
              description: Weekly digest delivery time in HH:MM format.
            weeklyDigestRunDay:
              type: number
              description: Day of the week for executing the weekly digest (0=Sunday).
            weeklyDigestRunHour:
              type: number
              description: Hour component when weekly digest is executed.
            weeklyDigestRunMinute:
              type: number
              description: Minute component when weekly digest is executed.
            sendReviewSmsAlert:
              type: number
              description: Flag to enable sending of review SMS alerts.
            sendDailySocialDigest:
              type: number
              description: Flag to enable sending of daily social media digests.
            sendTicketAlert:
              type: number
              description: Flag to enable sending of alerts when a new ticket is created.
            sendTicketStatusAlert:
              type: number
              description: Flag to enable sending of alerts when a ticket status changes.
            sendTicketAssigneeChangeAlert:
              type: number
              description: Flag to enable sending of alerts when ticket assignee changes.
            sendTicketCommentAlert:
              type: number
              description: Flag to enable sending of alerts when comments are added to tickets.
            sendTicketStartOrStoppedWatchingAlert:
              type: number
              description: Flag to enable sending of alerts when watching status changes for tickets.
            sendSurveyAlert:
              type: number
              description: Flag to enable sending of survey invitation alerts.
            sendReferralAlert:
              type: number
              description: Flag to enable sending of referral alerts.
            sendScanToolSignUpAlert:
              type: number
              description: Flag to enable sending of scan tool signup alerts.
            webChatEmailInterval:
              type: string
              description: Interval for web chat email notifications (e.g., "15,M").
            webChatEmailAbsoluteTime:
              type: string
              description: Absolute time for web chat email notifications in HH:MM format.
            enableWebchat:
              type: number
              description: Flag to enable web chat notifications.
            enableTeamAlert:
              type: number
              description: Flag to enable team-wide alerts.
            reviewAlertRatings:
              type: array
              description: Array of review ratings that trigger alerts.
              items: {}
            messengerEmailConversationType:
              type: string
              description: Comma-separated conversation types for messenger email notifications.
            assignedToMeAlert:
              type: number
              description: Flag to enable alerts for items assigned to the current user.
            enableBrowserNotification:
              type: number
              description: Flag to enable browser push notifications.
            messengerReportEnable:
              type: number
              description: Flag to enable messenger report feature.
            appointmentBooking:
              type: number
              description: Flag to enable in-app appointment booking feature.
            appointmentFormsEnabled:
              type: number
              description: Flag to enable appointment forms.
            enableAIPostSuggestions:
              type: number
              description: Flag to enable AI-driven post suggestions.
            enablePostFailureEmail:
              type: number
              description: Flag to enable email alerts for post failures.
            enableDirectMessageEmail:
              type: number
              description: Flag to enable email alerts for direct messages.
            enablePostCommentsEmail:
              type: number
              description: Flag to enable email alerts for post comments.
            enableMentionsEmail:
              type: number
              description: Flag to enable email alerts when the user is mentioned.
            enableStoryMentionsEmail:
              type: number
              description: Flag to enable email alerts for story mentions.
            enableNewFollowersEmail:
              type: number
              description: Flag to enable email alerts for new followers.
            enableRetweetEmail:
              type: number
              description: Flag to enable email alerts when a post is retweeted.
            enableQuoteTweetEmail:
              type: number
              description: Flag to enable email alerts for quote tweets.
            enablePostFailureBrowserNotification:
              type: number
              description: Flag to enable browser notifications for post failures.
            paymentAlert:
              type: number
              description: Flag to enable payment-related alerts.
            sendBrokenIntegrationAlert:
              type: number
              description: Flag to enable in-app alerts for broken integrations.
            sendBrokenIntegrationEmail:
              type: number
              description: Flag to enable email alerts for broken integrations.
          description: user details
    1013Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1013
        message: Unknown user role
    1010Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1010
        message: No user found with the given id
    1014Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1014
        message: User role cannot be blank
    1052Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1052
        message: User email id cannot be blank
    1175Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1175
        message: No business found with the given id
    1057Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1057
        message: First name cannot be more than 50 characters
    1161Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1161
        message: Invalid API key
    1189Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1189
        message: User with given email id not found.
    89Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 89
        message: Rate limit exceeded
    Apiary_createUser_Request:
      type: object
      properties:
        firstName:
          type: string
          description: First name of the user.
        lastName:
          type: string
          description: Last name of the user.
        userEmailId:
          type: string
          description: Email Id of the user that’s being added to this business.
        phone:
          type: string
          description: Mobile number of the user.
        userRole:
          type: string
          description: User role. Valid values are "owner","admin". Default is "owner".
        sendInvite:
          type: boolean
          description: Whether to send invite email to the user. Default is `true`.
      required:
      - userEmailId
      - userRole
      example:
        firstName: Rhonda
        lastName: Spears
        userEmailId: rhonda.spears@example.com
        phone: 408-xxx-xxxx
        userRole: owner
        sendInvite: true
    1053Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1053
        message: User email id is invalid
    1160Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1160
        message: User is already associated with business.
    1177Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1177
        message: User is not authorized to perform any action on any business
    1054Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1054
        message: User email id cannot be more than 40 characters
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: Partner specific API key provided by Birdeye for data exchange.
x-refined-from:
- birdeye-birdeye-api-openapi.yml
- birdeye-openapi-original.yml
