openapi: 3.2.0
info:
  title: Birdeye Business Media API
  version: '1.0'
  description: 'Operations tagged Business Media across 2 of this provider''s published API definitions: birdeye-birdeye-api-openapi.yml, birdeye-openapi-original.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://api.birdeye.com
  description: Production
- url: https://api.birdeye.com/resources
tags:
- name: Business Media
  description: 'Add, delete and manage business media.


    Supported Media Size


    Photo: JPG or PNG. 720 x 720px. 10KB min.

    Video: 30 sec long. 720p or more upto 75MB.




    Note


    Uploaded media will be pushed to your google business profile (if connected) and other long tail directories only.'
paths:
  /v1/business/{businessNumber}/upload/media:
    post:
      summary: Add Media
      operationId: add-media
      tags:
      - Business Media
      parameters:
      - name: businessNumber
        in: path
        required: true
        description: Location Number, in case of SMB it will be Business Number.
        schema:
          type: string
        example: '169744180007807'
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 2175
                  message: Provided media category is not supported
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                media:
                  type: array
              required:
              - media
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/business/{businessNumber}/media/get:
    get:
      summary: Get Media
      operationId: get-media
      tags:
      - Business Media
      parameters:
      - name: businessNumber
        in: path
        required: true
        description: Location Number, in case of SMB it will be Business Number.
        schema:
          type: string
        example: '169744180007807'
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 89
                  message: Rate limit exceeded
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/business/{businessNumber}/update/media/{mediaId}:
    put:
      summary: Update Media
      operationId: update-media
      tags:
      - Business Media
      parameters:
      - name: businessNumber
        in: path
        required: true
        description: Location Number, in case of SMB it will be Business Number.
        schema:
          type: string
        example: '169744180007807'
      - name: mediaId
        in: path
        required: true
        description: Id of the media item.
        schema:
          type: string
        example: '62185029212'
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  message: Invalid media id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                mediaCategory:
                  type: string
              required:
              - mediaCategory
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
  /v1/business/{businessNumber}/media/delete:
    delete:
      summary: Delete Media
      operationId: delete-media
      tags:
      - Business Media
      parameters:
      - name: businessNumber
        in: path
        required: true
        description: Location Number, in case of SMB it will be Business Number.
        schema:
          type: string
        example: '169744180007807'
      responses:
        '200':
          description: HTTP 200 response
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  message: Invalid media id
      security:
      - apiKey: []
    servers:
    - url: https://api.birdeye.com
      description: Production
components:
  schemas:
    2176Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 400
        message: Category can not be empty
    1167Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1167
        message: API key is missing
    2174Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2174
        message: Unsupported media format
    2177Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 400
        message: Invalid media id
    Apiary_updateMedia_Request:
      type: object
      properties:
        mediaCategory:
          type: string
          description: 'Category for the media item. Possible values are:'
      required:
      - mediaCategory
      example:
        mediaCategory: INTERIOR
    1011Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1011
        message: Business id is invalid
    2270Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2270
        message: Unsupported Media Category for the business
    Apiary_addMedia_Response200:
      type: object
      required:
      - media
      properties:
        media:
          type: array
          items:
            type: object
            properties:
              mediaId:
                type: string
                description: Id of the media.
              url:
                type: string
                description: Url of the media item.
              mediaCategory:
                type: string
                description: Category for the media item.
              description:
                type: string
                description: Description of the media.
              mediaFormat:
                type: string
                description: Format of the Media.
          description: List of media items.
    2181Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2181
        message: Supported video format is MP4.
    2180Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2180
        message: The recommended Image size for Google media image is 250 pixels wide and 250 pixels tall.
    2175Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2175
        message: Provided media category is not supported
    1161Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 1161
        message: Invalid API key
    Apiary_getMedia_Response200:
      type: object
      properties:
        media:
          type: array
          items:
            type: object
            properties:
              mediaId:
                type: string
                description: Id of the media.
              url:
                type: string
                description: Url of the media item.
              mediaCategory:
                type: string
                description: Category for the media item.
              description:
                type: string
                description: Description of the media.
              mediaFormat:
                type: string
                description: Format of the Media.
          description: List of media items of the business.
    Apiary_addMedia_Request:
      type: object
      properties:
        media:
          type: array
          description: List of media items to be uploaded.
          items:
            type: object
            properties:
              url:
                type: string
                description: Url of the media item.
              mediaCategory:
                type: string
                description: 'Category for the media item. Possible values are:'
              description:
                type: string
                description: Description of the media.
              mediaFormat:
                type: string
                description: 'Format of the Media. Possible values are:'
            required:
            - url
            - mediaCategory
            - description
            - mediaFormat
      required:
      - media
      example:
        media:
        - url: https://images.pexels.com/photos/12128533/pexels-photo-12128533.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
          mediaCategory: TEAMS
          description: Image of the team
          mediaFormat: PHOTO
        - url: https://videos.pexels.com/video/123123/pexelsvideo-12323.mp4
          mediaCategory: ADDITIONAL
          description: Introductory video
          mediaFormat: VIDEO
    2171Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 2171
        message: URL is invalid
    89Model:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      example:
        code: 89
        message: Rate limit exceeded
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: Partner specific API key provided by Birdeye for data exchange.
x-refined-from:
- birdeye-birdeye-api-openapi.yml
- birdeye-openapi-original.yml
